config/routes.rb
TestApp::Application.routes.draw do
  get "static_pages/home"

  root 'static_pages#home'
  resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.create(car_params)
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :color, :year)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cars/index.html.erb
<% @cars.each do |car| %>
<div class="container col-xs-10 col-xs-offset-1">
  <h2><%= car.make %> <%= car.model %></h2>
  <i><%= car.year %></i>
  <p><%= car.color %></p>
</div>
  <% end %>

app/views/cars/new.html.erb
<div class="container col-xs-10 col-xs-offset-1">
<%= simple_form_for @car do |f| %>
<%= f.input :make %>
<%= f.input :model %>
<%= f.input :color %>
<%= f.input :year %>
<%= f.button :submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<div class="container col-xs-10 col-xs-offset-1">
  <h1>Lets talk about cars</h1>
  <p>Hello and welcome to my home page</p>
  <%= link_to "Add a car", new_car_path %> <br />
  <%= link_to "List of Cars", cars_path %>
</div>